language: python
sudo: false

python:
  - "3.6"
  - "3.5"

# command to install dependencies
install:
  - "pip install . pytest coverage"
# command to run tests
script:
  - RUNCOVERAGE=1 tests/run_tests.sh

jobs:
  include:
    - python: 3.6
      install:
        - FORCE_HAL_INSTALL=1 pip install robotpy-hal-roborio pybind11
      script:
        - python setup.py build
    - stage: deploy
      python: 3.6
      if: tag IS present
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
